#!/usr/bin/env python3
"""Routing-manifest drift check.

Verifies that every skill present in skills/INDEX.json appears in the
routing manifest output (generated by scripts/routing-manifest.py).
A skill absent from the manifest is invisible to the router.

skills/INDEX.json is a generated, untracked artifact (ADR untrack-generated-indexes).
If it is missing (fresh checkout), this script generates it first, then validates,
rather than failing on a missing tracked file.

Usage:
    python3 scripts/check-routing-drift.py
    python3 scripts/check-routing-drift.py --verbose

Exit codes:
    0 - All skills in INDEX.json appear in the routing manifest
    1 - Index could not be produced, or one or more skills are absent from the manifest
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SKILLS_INDEX = REPO_ROOT / "skills" / "INDEX.json"
SKILLS_INDEX_GENERATOR = REPO_ROOT / "scripts" / "generate-skill-index.py"
MANIFEST_SCRIPT = REPO_ROOT / "scripts" / "routing-manifest.py"


def _ensure_skills_index() -> bool:
    """Ensure skills/INDEX.json exists, generating it if missing.

    INDEX.json is an untracked, generated artifact (ADR untrack-generated-indexes),
    so on a fresh checkout it may be absent. Generate it rather than failing.
    Returns True if the index is present (or was generated), False otherwise.
    """
    if SKILLS_INDEX.exists():
        return True
    if not SKILLS_INDEX_GENERATOR.exists():
        print(f"ERROR: {SKILLS_INDEX} missing and generator not found", file=sys.stderr)
        return False
    result = subprocess.run(
        [sys.executable, str(SKILLS_INDEX_GENERATOR)],
        capture_output=True,
        text=True,
        cwd=str(REPO_ROOT),
    )
    if result.returncode != 0:
        print(f"ERROR: failed to generate {SKILLS_INDEX}: {result.stderr}", file=sys.stderr)
        return False
    return SKILLS_INDEX.exists()


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--verbose", action="store_true", help="Show all skills checked")
    args = parser.parse_args()

    if not _ensure_skills_index():
        return 1

    if not MANIFEST_SCRIPT.exists():
        print(f"ERROR: {MANIFEST_SCRIPT} not found", file=sys.stderr)
        return 1

    with open(SKILLS_INDEX) as f:
        idx = json.load(f)

    index_skills = sorted(idx.get("skills", {}).keys())

    # Generate manifest and check each skill appears
    result = subprocess.run(
        [sys.executable, str(MANIFEST_SCRIPT)],
        capture_output=True,
        text=True,
        cwd=str(REPO_ROOT),
    )
    if result.returncode != 0:
        print(f"ERROR: routing-manifest.py failed: {result.stderr}", file=sys.stderr)
        return 1

    manifest_text = result.stdout

    missing = [s for s in index_skills if s not in manifest_text]
    present = [s for s in index_skills if s in manifest_text]

    if args.verbose:
        print(f"Checked {len(index_skills)} skills against routing manifest")
        print(f"  Present: {len(present)}")
        print(f"  Missing: {len(missing)}")

    if missing:
        print(f"\nFAIL: {len(missing)} skill(s) in INDEX.json absent from routing manifest:")
        for skill in missing:
            print(f"  {skill}")
        print("\nEnsure each skill has valid INDEX.json entry and routing-manifest.py renders it.")
        return 1

    if args.verbose:
        print("\nPASS: routing manifest is in sync with INDEX.json")
    return 0


if __name__ == "__main__":
    sys.exit(main())
